import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ReactQueryProvider from '@/utils/providers/ReactQueryProvider';

import './globals.css';
import Header from '@/app/components/header/Header';

const helveticaNeue = localFont({
  src: [
    {
      path: '../public/fonts/helveticaneue-light.woff2',
      weight: '200',
    },
    {
      path: '../public/fonts/helveticaneue-regular.woff2',
      weight: '400',
    },
    {
      path: '../public/fonts/helveticaneue-bold.woff2',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={helveticaNeue.className}>
        <Header
          title="Star Wars Characters"
          subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
        />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
